foreground         #c6c7c8
background         #1e1f25
background_opacity 1.0
cursor             #c6c7c8

active_tab_foreground     #1e1f25
active_tab_background     #c6c7c8
inactive_tab_foreground   #c6c7c8
inactive_tab_background   #1e1f25

active_border_color   #c6c7c8
inactive_border_color #1e1f25
bell_border_color     #605e4a

color0       #1e1f25
color8       #636779
color1       #605e4a
color9       #817E63
color2       #5a6350
color10      #79846B
color3       #6c6c53
color11      #90916F
color4       #787558
color12      #A09D76
color5       #7d7b5c
color13      #A7A57B
color6       #878566
color14      #B4B289
color7       #95989f
color15      #c6c7c8
